version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: rural-insights-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/__pycache__
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=development
    env_file:
      - ./backend/.env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - rural-insights-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: rural-insights-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
    command: npm run dev
    networks:
      - rural-insights-network
    depends_on:
      - backend

networks:
  rural-insights-network:
    driver: bridge

volumes:
  node_modules:
  venv: